# 工作流程的名稱
name: Build Markdown to PDF

# 觸發條件：當有程式碼被 push 到 main 分支時執行
on:
  push:
    branches:
      - main  # 您可以改成您的主要分支名稱，例如 master

# 要執行的任務
jobs:
  build-pdf:
    # 執行任務的虛擬環境，使用最新的 Ubuntu
    runs-on: ubuntu-latest

    # 任務中的步驟
    steps:
      # 步驟一：將您的倉庫程式碼下載到虛擬環境中
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步驟二：安裝必要的 LaTeX 套件
      - name: Install LaTeX packages
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-lang-chinese fonts-noto-cjk

      # 步驟三：使用 Pandoc 進行轉換
      - name: Convert Markdown to PDF with Pandoc
        uses: docker://pandoc/core:latest
        with:
          args: >-
            --standalone
            hw.md
            --pdf-engine=xelatex
            -V CJKmainfont="Noto Sans CJK TC"
            -o hw2.pdf

      # 步驟四：上傳生成的 PDF 作為「產物」(Artifact)
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          # 產物的名稱
          name: Generated-PDF
          # 要上傳的檔案路徑
          path: hw2.pdf